In [1]:

# original outputs 12 29 32 23
    
    
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('E:\\test.csv',nrows=4)

In [3]:
train = data[['a','b']]
y     = data.c.values
y

array([12, 29, 32, 23], dtype=int64)

In [4]:
train

a  b
0  2  3
1  8  7
2  8  4
3  5  2

In [5]:
train.shape[1],1
x=train

In [6]:
w= np.zeros((train.shape[1], 1))
eta = 0.03
iterations = 15
m = train.shape[0]
w

array([[0.],
       [0.]])

In [7]:
train.T

0  1  2  3
a  2  8  8  5
b  3  7  4  2

# without intercept

In [8]:
for it in range(1000+1):
    y_pred = np.dot(train,w)
    residues = y_pred - y.reshape([train.shape[0],1])
    gv = np.dot(train.T,residues)
    w  -= eta/m * gv
    cost = np.sum((residues ** 2)) / (2 * m)
    if it%100 ==0 :
        print(it,"th iteration")
        print("y= ",y)
        print("y_pred = ",y_pred)
        print("residues = ",residues)
        print("gv =",gv)
        print("w =",w)
        print("cost ", cost,"\n\n")

0 th iteration
y=  [12 29 32 23]
y_pred =  [[0.]
 [0.]
 [0.]
 [0.]]
residues =  [[-12.]
 [-29.]
 [-32.]
 [-23.]]
gv = [[-627.]
 [-413.]]
w = [[4.7025]
 [3.0975]]
cost  317.25 


100 th iteration
y=  [12 29 32 23]
y_pred =  [[ 7.58555425]
 [31.53837275]
 [32.25606621]
 [20.27965696]]
residues =  [[-4.41444575]
 [ 2.53837275]
 [ 0.25606621]
 [-2.72034304]]
gv = [[-0.07509507]
 [ 0.10885073]]
w = [[ 4.15218707]
 [-0.24004753]]
cost  4.174562963131693 


200 th iteration
y=  [12 29 32 23]
y_pred =  [[ 7.55757436]
 [31.51279919]
 [32.28230024]
 [20.30468782]]
residues =  [[-4.44242564]
 [ 2.51279919]
 [ 0.28230024]
 [-2.69531218]]
gv = [[-0.00061676]
 [ 0.000894  ]]
w = [[ 4.16354233]
 [-0.25650705]]
cost  4.174213310300607 


300 th iteration
y=  [12 29 32 23]
y_pred =  [[ 7.55734456]
 [31.51258915]
 [32.2825157 ]
 [20.3048934 ]]
residues =  [[-4.44265544]
 [ 2.51258915]
 [ 0.2825157 ]
 [-2.6951066 ]]
gv = [[-5.06551550e-06]
 [ 7.34249383e-06]]
w = [[ 4.16363559]
 [-0.25664224]]
cost  4.17

## weights and coefficients are equal


In [9]:
lr = LinearRegression(copy_X=True,fit_intercept=False,n_jobs=None,normalize=False)
lr.fit(train,y)
print(lr.coef_)
print(lr.intercept_)
w

[ 4.16363636 -0.25664336]
0.0


array([[ 4.16363636],
       [-0.25664336]])

# with intercept

In [10]:
w2= np.zeros((train.shape[1]+1, 1))
x = train.assign(bais=1)
x

a  b  bais
0  2  3     1
1  8  7     1
2  8  4     1
3  5  2     1

In [11]:
for it in range(3000+1):
    y_pred = np.dot(x,w2)
    residues = y_pred - y.reshape([x.shape[0],1])
    gv = np.dot(x.T,residues)
    w2  -= eta/m * gv
    cost = np.sum((residues ** 2)) / (2 * m)    
    if(it%100==0):
        print(it,"th  iteration")
        print("y= ",y)
        print("y_pred = ",y_pred)
        print("residues = ",residues)
        print("gv =",gv)
        print("w2 =",w2)
        print("cost ", cost,"\n\n")

0 th  iteration
y=  [12 29 32 23]
y_pred =  [[0.]
 [0.]
 [0.]
 [0.]]
residues =  [[-12.]
 [-29.]
 [-32.]
 [-23.]]
gv = [[-627.]
 [-413.]
 [ -96.]]
w2 = [[4.7025]
 [3.0975]
 [0.72  ]]
cost  317.25 


100 th  iteration
y=  [12 29 32 23]
y_pred =  [[ 9.21858785]
 [30.66498021]
 [32.07892073]
 [21.35572455]]
residues =  [[-2.78141215]
 [ 1.66498021]
 [ 0.07892073]
 [-1.64427545]]
gv = [[ 0.16700595]
 [ 0.33775702]
 [-2.68178666]]
w2 = [[ 3.88735519]
 [-0.47384669]
 [ 2.87542631]]
cost  1.6522853592232742 


200 th  iteration
y=  [12 29 32 23]
y_pred =  [[10.11850797]
 [30.11242475]
 [32.00053358]
 [22.00357519]]
residues =  [[-1.88149203e+00]
 [ 1.11242475e+00]
 [ 5.33577499e-04]
 [-9.96424813e-01]]
gv = [[ 0.15855849]
 [ 0.15178183]
 [-1.76495852]]
w2 = [[ 3.75071001]
 [-0.63050797]
 [ 4.51605558]]
cost  0.7212954726656577 


300 th  iteration
y=  [12 29 32 23]
y_pred =  [[10.72847185]
 [29.76555955]
 [31.93199655]
 [22.4134527 ]]
residues =  [[-1.27152815]
 [ 0.76555955]
 [-0.06800345]
 

2700 th  iteration
y=  [12 29 32 23]
y_pred =  [[11.89995004]
 [29.10002839]
 [31.80000563]
 [23.19996645]]
residues =  [[-0.10004996]
 [ 0.10002839]
 [-0.19999437]
 [ 0.19996645]]
gv = [[ 4.46370536e-06]
 [ 4.23150912e-06]
 [-4.94951564e-05]]
w2 = [[ 3.46667463]
 [-0.89999245]
 [ 7.66657831]]
cost  0.012500000557400415 


2800 th  iteration
y=  [12 29 32 23]
y_pred =  [[11.89996715]
 [29.10001866]
 [31.8000037 ]
 [23.19997794]]
residues =  [[-0.10003285]
 [ 0.10001866]
 [-0.1999963 ]
 [ 0.19997794]]
gv = [[ 2.93500230e-06]
 [ 2.78232724e-06]
 [-3.25443520e-05]]
w2 = [[ 3.46667191]
 [-0.89999503]
 [ 7.66660857]]
cost  0.012500000240986648 


2900 th  iteration
y=  [12 29 32 23]
y_pred =  [[11.8999784 ]
 [29.10001227]
 [31.80000243]
 [23.1999855 ]]
residues =  [[-0.1000216 ]
 [ 0.10001227]
 [-0.19999757]
 [ 0.1999855 ]]
gv = [[ 1.92984033e-06]
 [ 1.82945249e-06]
 [-2.13987574e-05]]
w2 = [[ 3.46667011]
 [-0.89999673]
 [ 7.66662847]]
cost  0.012500000104188133 


3000 th  iteration
y=  [1

# weigths and coefficients are equal

In [12]:
lr2 = LinearRegression(copy_X=True,fit_intercept=True,n_jobs=None,normalize=False)
lr2.fit(train,y)
print(lr2.coef_)
print(lr2.intercept_)
w2

[ 3.46666667 -0.9       ]
7.666666666666668


array([[ 3.46666893],
       [-0.89999785],
       [ 7.66664155]])